import Intro from "./intro-img-3.png"
import Bear from "./bear.png"
import twentyfive from "./1025.png"
import Cat from "./cat.png"
import DogBig from "./dog-big.png"
import MushroomBig from "./mushroom-big.png"
import MushroomLittleOne from "./mushroom-little-1.png"
import MushroomLittleTwo from "./mushroom-little-2.png"
import PersonBig from "./person-big.png"
import PersonLittleOne from "./person-little-1.png"
import PersonLittleTwo from "./person-little-2.png"
import PersonOne from "./person-1.png"
import PersonTwo from "./person-2.png"
import PersonThree from "./person-3.png"
import PersonFour from "./person-4.png"
import PersonFive from "./person-5.png"
import PersonSix from "./person-6.png"
import PersonSeven from "./person-7.png"
import PersonEight from "./person-8.png"
import PersonNine from "./person-9.png"
import PersonTen from "./person-10.png"
import PersonEleven from "./person-11.png"
import PersonOnikki from "./person-12.png"
import CategoryOne from "./category-1.png"
import CategoryTwo from "./category-2.png"
import CategoryThree from "./category-3.png"
import CategoryFour from "./category-4.png"
import CategoryFive from "./category-5.png"
import CategorySix from "./category-6.png"
import CategorySeven from "./category-7.png"
import CategoryEight from "./category-8.png"
import NftOne from "./nft-1.png"
import NftTwo from "./nft-2.png"
import NftThree from "./nft-3.png"


export {Intro,Bear,twentyfive,Cat,DogBig,MushroomBig,MushroomLittleOne,MushroomLittleTwo,PersonLittleOne,PersonLittleTwo,PersonBig,PersonOne,PersonTwo,PersonThree,PersonFour,PersonFive,PersonSix,PersonSeven,PersonEight,PersonNine,PersonTen,PersonEleven,PersonOnikki,CategoryOne,CategoryTwo,CategoryThree,CategoryFour,CategoryFive,CategorySix,CategorySeven,CategoryEight,NftOne,NftTwo,NftThree}