import Logo from "./logo.svg"
import Favicon from "./favicon.svg"
import YouTube from "./youtube.svg"
import Discord from "./discord.svg"
import Insta from "./insta.svg"
import Twitter from "./twitter.svg"
import Extra from "./extra.svg"
import Avatar from "./avatar-person.svg"
import FoxAva from "./fox-ava.svg"
import ChinaAva from "./china-ava.svg"
import RoboAva from "./robot.svg"
import NftAvaOne from "./nft-logo-1.svg"
import NftAvaTwo from "./nft-logo-2.svg"
import NftAvaThree from "./nft-logo-3.svg"

export {Logo,Favicon,YouTube,Discord,Insta,Twitter,Extra,Avatar,FoxAva,ChinaAva,RoboAva,NftAvaOne,NftAvaTwo,NftAvaThree}